# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/county-image-classifier
    docker:
      # specify the version you desire here
      - image: circleci/python:3.6.7

    steps:
      - checkout
        # Download and cache dependencies
      #- restore_cache:
      #    keys:
      #    - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
      #    - v1-dependencies-

      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv project_env
            . project_env/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./project_env
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run prediction tests
          command: |
            . project_env/bin/activate
            PYTHONPATH=./county_classifier python county_classifier/tests/test_image_predictor.py

    #  - run:
    #      name: run evaluation tests
    #      command: |
     #       cd lab9 && PYTHONPATH=. pipenv run pytest -s evaluation/*
    #  - store_artifacts:
    #      path: test-reports
    #      destination: test-reports
